image: elixir:1.8.1-slim

services:
  - postgres:latest

variables:
  POSTGRES_DB: test_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  # Installing required libs:
  - apt-get update && apt-get -y install postgresql-client
  # Installing elixir deps:
  - mix local.hex --force && mix local.rebar --force && mix deps.get

test:
  stage: test
  script:
    - mix credo
    - mix test
  coverage: '\[TOTAL\]\s+(\d+\.\d+)%'
