language: elixir

sudo: false

elixir:
  - 1.8.2

addons:
  postgresql: "9.6"

env:
  - MIX_ENV="test";
    KIRA_GITLAB_SECRET_HEADER_VALUE="123";
    KIRA_GITLAB_PERSONAL_TOKEN="fake";

before_install:
  - mix local.hex --force && mix local.rebar --force

install:
  - mix do deps.get, deps.compile

before_script:
  # Setting up database:
  - mix ecto.reset

script:
  - mix format --check-formatted
  - mix credo
  # TODO: enable HTTPS
  - mix sobelow --private -i Config.HTTPS
  - mix coveralls.travis --timeout 1000

notifications:
  email: false
